/* Used Laptop Buying Guidelines — single-file JavaScript application.
   Deliberately uses classic JavaScript (not ES modules) so index.html can be opened
   directly from a local file:// URL and deployed unchanged to GitHub Pages.
*/
(function(){
'use strict';

const T=(id,title,sectionKey,purpose,gui,steps,command,where,expected,interpretation,warnings=[],platform='Windows 10/11',next='পরের test-এ যাও।',admin=false)=>({id,title,sectionKey,purpose,gui,steps,command,where,expected,interpretation,warnings,platform,next,admin});
const inspectionSections=[
{id:'identity',title:'Part 1 — Laptop Identity & Configuration',tests:[
T('system-info','System Information','identity','(মেশিনের model, BIOS এবং মূল configuration seller-এর তথ্যের সঙ্গে মিলিয়ে দেখার জন্য)','Start → Search → System Information → System Information খুলুন',['System Manufacturer, System Model, System Type, Processor, BIOS Version/Date, Installed Physical Memory, BaseBoard Manufacturer/Product/Version খুঁজুন।'],'msinfo32','Command Prompt / Run','উল্লিখিত system ও baseboard fields দেখা যাবে।','এগুলো seller-এর specification, invoice ও laptop label-এর সঙ্গে মিলিয়ে দেখুন।',['Model বা serial তথ্য অমিল হলে কারণ যাচাই করুন।']),
T('cpu-info','CPU Information','cpu','(আসল processor model, cores ও logical processors যাচাই করার জন্য)','Task Manager → Performance → CPU; অথবা System Information',['CPU Name, Manufacturer, Number of Cores এবং Logical Processors নোট করুন।'],'Get-CimInstance Win32_Processor | Select-Object Name,Manufacturer,NumberOfCores,NumberOfLogicalProcessors,MaxClockSpeed','PowerShell','CPU-এর নাম ও core/thread তথ্য আসবে।','Seller-এর CPU claim-এর সঙ্গে exact model মিলিয়ে দেখুন।',[]),
T('cpu-load','CPU Load / Performance Observation','cpu','(idle ও workload-এ CPU অস্বাভাবিক আচরণ করছে কি না দেখতে)','Task Manager → Performance → CPU',['5–10 মিনিট স্বাভাবিক idle অবস্থায় usage, clock ও responsiveness দেখুন; তারপর browser/file operation দিয়ে আচরণ দেখুন।'],'','Task Manager','Idle ও light-use-এ usage/clock পরিবর্তন হবে; fixed universal value নেই।','Background update/app usage-এর কারণে load বদলাতে পারে—একটি snapshot দিয়ে সিদ্ধান্ত নেবেন না।',['দীর্ঘক্ষণ অস্বাভাবিক 100% load, severe stutter বা unexpected shutdown নোট করুন।'])]},
{id:'gpu',title:'Part 2 — GPU',tests:[
T('gpu-info','GPU Information','gpu','(GPU model, driver ও DirectX তথ্য যাচাই করার জন্য)','Task Manager → Performance → GPU; Device Manager → Display adapters; Run → dxdiag',['GPU model, driver এবং available memory-related fields দেখুন।'],'dxdiag','Run / Command Prompt','DirectX Diagnostic Tool খুলবে।','GPU model/driver seller claim-এর সঙ্গে মিলিয়ে দেখুন।',['Device Manager warning icon বা driver error থাকলে আলাদা করে পরীক্ষা করুন।']),
T('gpu-stress','GPU Stress / Load Test','gpu','(বাস্তব load-এ GPU stability ও visual behavior পর্যবেক্ষণের জন্য)','Task Manager → Performance → GPU; নিরাপদ graphical workload যেমন browser 3D demo বা আপনার পরিচিত application',['GPU usage, clock এবং display stability দেখুন; artifact, driver crash, black screen বা restart আছে কি না নোট করুন।'],'','Task Manager / পরিচিত application','Load অনুযায়ী GPU usage বাড়বে; temperature/clock model ও workload অনুযায়ী পরিবর্তিত হবে।','একটি universal temperature pass/fail threshold নেই। দীর্ঘমেয়াদি stability এবং symptoms বেশি গুরুত্বপূর্ণ।',['Artifact, black screen, driver crash বা restart হলে আরও inspection দরকার।'])]},
{id:'ram',title:'Part 3 — RAM',tests:[
T('ram-info','RAM Capacity / Speed','ram','(RAM-এর capacity, speed, module location ও configured clock যাচাই করার জন্য)','Task Manager → Performance → Memory',['Capacity, speed, slots used এবং form factor যেখানে দেখায় নোট করুন।'],'Get-CimInstance Win32_PhysicalMemory | Select-Object Manufacturer,PartNumber,Capacity,Speed,ConfiguredClockSpeed,DeviceLocator','PowerShell','প্রতি memory module-এর manufacturer/part/size/speed/location তথ্য আসবে।','Total RAM seller claim-এর সঙ্গে মিলিয়ে দেখুন; speed platform-এর supported behavior অনুযায়ী বুঝুন.',[]),
T('ram-error','RAM Error Test','ram','(memory error আছে কি না শনাক্ত করার জন্য)','Start → Search → Windows Memory Diagnostic → Restart now and check for problems',['আগে unsaved work save করুন, তারপর diagnostic চালান এবং result নোট করুন।'],'mdsched.exe','Run / Start Search','Windows Memory Diagnostic restart-এর পর memory পরীক্ষা করবে।','Error report হলে RAM/module/slot নিয়ে আরও diagnosis প্রয়োজন।',['Memory error পাওয়া গুরুত্বপূর্ণ warning।'],'Windows 10/11', 'Advanced test হিসেবে MemTest86 ব্যবহার করা যেতে পারে।'),
T('ram-upgrade','RAM Upgradeability','ram','(ভবিষ্যতে RAM বাড়ানো যাবে কি না জানার জন্য)','Task Manager slots information + exact model/service manual/specification যাচাই করুন',['Soldered RAM, available slots এবং maximum supported capacity নিশ্চিত করুন।'],'','Manufacturer documentation / service manual','Exact model-এর supported RAM configuration পাওয়া উচিত।','শুধু current RAM দেখে upgrade compatibility অনুমান করবেন না।',['No free slot বা soldered-only configuration থাকলে upgrade সীমিত হতে পারে।'])]},
{id:'storage',title:'Part 4 — SSD / HDD',tests:[
T('storage-info','Storage Information','storage','(disk model, capacity, bus ও health fields যাচাই করার জন্য)','Settings → System → Storage; Task Manager → Performance → Disk',['Disk model, capacity ও interface/bus information মিলিয়ে দেখুন।'],'Get-Disk | Format-Table Number,FriendlyName,SerialNumber,BusType,HealthStatus,OperationalStatus,Size','PowerShell','Disk number, model, serial, bus, health, operational status ও size দেখা যাবে।','Seller-এর SSD/HDD claim-এর সঙ্গে exact device মিলিয়ে দেখুন।',[]),
T('physical-disk','Physical Disk Health','storage','(Windows-এর basic disk health status দেখার জন্য)','PowerShell / Computer Management → Disk Management',['HealthStatus ও OperationalStatus দেখুন।'],'Get-PhysicalDisk | Format-Table FriendlyName,MediaType,BusType,HealthStatus,OperationalStatus,Size','PowerShell','Physical disk health/status fields আসবে।','Windows basic health complete SMART analysis নয়।',['Warning বা unhealthy status হলে advanced inspection করুন।']),
T('smart','SSD/HDD SMART','storage','(drive-এর deeper SMART attributes ও warning দেখার জন্য)','Advanced: CrystalDiskInfo-এর মতো reputable tool ব্যবহার করে SMART attributes পড়ুন।',['Power-on hours, health indicators, reallocated/uncorrectable indicators যেখানে applicable এবং temperature দেখুন।'],'','Third-party diagnostic tool','Drive-specific SMART attributes দেখা যাবে; field names device অনুযায়ী বদলাতে পারে।','SMART data একটি useful evidence source, complete hardware certification নয়।',['Critical SMART warning বা rapidly worsening indicators হলে আরও inspection দরকার।']),
T('ssd-speed','SSD Speed','storage','(storage performance অস্বাভাবিক কি না যাচাই করার জন্য)','Advanced: CrystalDiskMark বা আপনার পরিচিত non-destructive benchmark; গুরুত্বপূর্ণ data থাকলে সতর্ক থাকুন।',['Read/write results record করুন এবং একই drive/interface class-এর expected specification-এর সঙ্গে তুলনা করুন।'],'','Third-party benchmark','Benchmark read/write figures দেখাবে।','Benchmark result workload, thermal state, free space ও interface-এর উপর নির্ভর করে।',['Severe slowdown, errors বা crashes হলে cause যাচাই করুন।'])]},
{id:'display',title:'Part 5 — Display',tests:[
T('display-mode','Resolution / Refresh Rate','display','(panel-এর configured resolution ও refresh rate যাচাই করার জন্য)','Settings → System → Display → Advanced display',['Resolution, refresh rate এবং display identity দেখুন।'],'','Settings','Current display mode দেখা যাবে।','Seller claim ও panel specification-এর সঙ্গে মিলিয়ে দেখুন।',[]),
T('dead-pixel','Dead Pixel Test','display','(dead/stuck pixel ও uneven display area শনাক্ত করার জন্য)','Browser-এ full-screen white, black, red, green, blue test pages দেখুন।',['Screen পরিষ্কার করুন; পাঁচটি solid color-এ পুরো panel দেখুন।'],'','Browser','Solid colors-এ pixel-level anomalies চোখে পড়বে।','একটি fixed pixel issue থাকলে location ও appearance নোট করুন; stuck/dead classification নিশ্চিত করতে multiple colors দেখুন।',['Line, cluster, persistent dot বা discoloration নোট করুন।']),
T('screen-angle','Screen Angle Test','display','(hinge movement ও panel viewing-angle behavior যাচাই করার জন্য)','Desktop থেকে বিভিন্ন lid angle-এ screen দেখুন।',['ধীরে lid angle পরিবর্তন করুন এবং image flicker/cut-out আছে কি না দেখুন।'],'','Physical inspection','Normal angle changes-এ image stable থাকা উচিত।','Angle change-এ display cut হলে cable/hinge/panel issue হতে পারে।',['Flicker বা blackout হলে further repair inspection দরকার।']),
T('brightness','Brightness Test','display','(brightness control ও panel uniformity যাচাই করার জন্য)','Settings → System → Display → Brightness; solid colors দেখুন',['Low/medium/high brightness-এ uniformity ও flicker দেখুন।'],'','Settings','Brightness changes should be observable without instability.','Panel type ও auto-brightness behavior অনুযায়ী appearance বদলাতে পারে।',['Persistent flicker, dark patches বা pressure marks নোট করুন।'])]},
{id:'battery',title:'Part 6 — Battery',tests:[
T('battery-report','Battery Report','battery','(battery design capacity ও current full charge capacity-এর evidence পাওয়ার জন্য)','Start → Search → Command Prompt → Run as appropriate; report file তৈরি হওয়ার path দেখুন',['Report খুলে Design Capacity, Full Charge Capacity, Cycle Count when available এবং recent usage দেখুন।'],'powercfg /batteryreport','Command Prompt','Windows একটি battery-report.html তৈরি করবে এবং path জানাবে।','Capacity difference-কে context সহ দেখুন; battery age, cycles ও behavior বিবেচনা করুন।',['Swelling বা physical deformation হলে ব্যবহার বন্ধ করে safety handling করুন।']),
T('battery-real','Real Battery Test','battery','(বাস্তব ব্যবহারে battery drain ও charging behavior পর্যবেক্ষণের জন্য)','Unplug charger; normal browsing/video workload-এ time-stamped battery percentage নোট করুন',['Known workload ব্যবহার করুন; screen brightness ও power mode নোট করুন।'],'','Windows battery indicator / stopwatch','সময় অনুযায়ী battery percentage পরিবর্তন হবে।','একটি short test universal battery-health percentage দেয় না; observed runtime context সহ নোট করুন।',[]),
T('battery-swelling','Battery Swelling','battery','(সুরক্ষা ঝুঁকি হিসেবে battery deformation শনাক্ত করার জন্য)','Body/palmrest/trackpad bulge, uneven bottom cover বা separation visually inspect করুন।',['কোনো swelling সন্দেহ হলে laptop খুলবেন না বা battery চাপ দেবেন না।'],'','Physical inspection','কোনো bulge/separation না থাকাই expected visual condition।','Swelling হলে এটি safety concern; qualified service professional-এর সাহায্য নিন।',['Battery swelling — critical attention'])]},
{id:'charger',title:'Part 7 — Charger & Charging',tests:[
T('charger','Charger','charger','(সঠিক charger rating ও stable charging যাচাই করার জন্য)','Charger label + Windows charging indicator + exact model documentation',['Voltage, current, polarity/connector যেখানে applicable এবং wattage মিলিয়ে দেখুন।'],'','Physical inspection','Charger label-এ rating থাকবে এবং laptop stableভাবে charge করবে।','Watt = Volt × Ampere; exact manufacturer requirement-এর সঙ্গে compare করুন।',['Non-original/underpowered charger বা unstable charging নোট করুন।']),
T('charging-port','Charging Port','charger','(port loose/damaged কি না যাচাই করার জন্য)','Charger plug gently connect করে charging indicator ও connection stability দেখুন',['Plug নাড়াচাড়া করে force করবেন না; normal position-এ charging stable কিনা দেখুন।'],'','Physical inspection','Stable connection থাকা উচিত।','Loose port intermittent charging বা repair need-এর evidence হতে পারে।',['Port heat, looseness, sparks বা intermittent charging হলে সতর্ক হন।'])]},
{id:'input',title:'Part 8 — Keyboard & Touchpad',tests:[
T('keyboard','Keyboard','input','(সব key ও special function কাজ করছে কি না যাচাই করার জন্য)','Browser text field বা keyboard tester; প্রয়োজনীয় function keys system-এ পরীক্ষা করুন',['A-Z, 0-9, Function keys, Enter, Shift, Ctrl, Alt, Tab, Caps Lock, Backspace, Space, Arrow, Delete, Windows, Esc এবং special keys পরীক্ষা করুন।'],'','Browser / Physical inspection','প্রতিটি tested key expected input দেবে।','Backlight/special keys model-specific; exact model documentation দেখুন।',['Multiple dead keys, sticky keys বা liquid residue নোট করুন।']),
T('touchpad','Touchpad','input','(cursor, clicks, scrolling ও gestures যাচাই করার জন্য)','Windows touchpad settings + desktop/browser',['Move, left click, right click, scroll, drag/drop এবং supported gestures পরীক্ষা করুন।'],'','Windows Settings / Physical test','Pointer movement ও clicks stable থাকবে।','Gestures model/driver-dependent; unsupported gesture নিজে defect নয়।',['Erratic cursor, dead zones বা intermittent click নোট করুন।'])]},
{id:'av',title:'Part 9 — Audio / Microphone / Webcam',tests:[
T('speaker','Speaker','av','(speaker distortion ও channel behavior যাচাই করার জন্য)','Settings → System → Sound → Output; পরিচিত audio চালান',['Low/medium/high volume-এ distortion, crackle এবং left/right channel শুনুন।'],'','Windows Sound settings','Audio output শোনা যাবে এবং volume change কাজ করবে।','Source recording quality-ও speaker test-এ প্রভাব ফেলে।',['Persistent crackle, cut-out বা one-channel failure নোট করুন।']),
T('headphone','Headphone Jack','av','(3.5mm audio port কাজ করছে কি না যাচাই করার জন্য)','Headphones connect করে Sound output/input behavior পরীক্ষা করুন',['Plug detect ও audio output যাচাই করুন।'],'','Windows Sound settings','Headphone connection অনুযায়ী output route হবে যেখানে device supports it।','USB/Bluetooth audio আলাদা; 3.5mm jack capability model-specific।',[]),
T('microphone','Microphone','av','(built-in/external microphone recording যাচাই করার জন্য)','Settings → System → Sound → Input অথবা Voice Recorder',['Short recording করুন এবং playback-এ clarity, noise ও drop-out শুনুন।'],'','Windows Sound settings','Input level ও recorded audio দেখা/শোনা যাবে।','Room noise এবং privacy settings ফলাফলে প্রভাব ফেলতে পারে।',['No input, severe static বা intermittent recording নোট করুন।']),
T('webcam','Webcam','av','(camera image, focus ও privacy shutter behavior যাচাই করার জন্য)','Windows Camera app খুলুন',['Preview image, flicker, artifacts ও privacy shutter পরীক্ষা করুন।'],'','Camera app','Camera preview দেখা যাবে।','Privacy shutter থাকলে manually open করতে হবে।',['Black image, severe flicker বা artifact নোট করুন।'])]},
{id:'wireless',title:'Part 10 — Wi-Fi / Bluetooth',tests:[
T('wifi','Wi-Fi','wireless','(Wi-Fi adapter, connection এবং signal information যাচাই করার জন্য)','Settings → Network & Internet → Wi-Fi; known network-এ connect করুন',['SSID, signal এবং connection stability দেখুন।'],'netsh wlan show interfaces','Command Prompt','Interface, state, SSID, radio type এবং signal-related information দেখা যাবে।','Adapter model এবং actual connection performance record করুন।',['Repeated disconnect বা adapter error হলে further inspection দরকার।']),
T('network','Network Adapter','wireless','(network adapter inventory ও IP configuration যাচাই করার জন্য)','Settings → Network & Internet; Device Manager → Network adapters',['Adapter name, status ও IPv4/IPv6 configuration দেখুন।'],'ipconfig /all','Command Prompt','Adapters, MAC-related identifiers, DHCP/DNS এবং IP information দেখা যাবে।','MAC address publicভাবে share না করাই ভালো।',[]),
T('bluetooth','Bluetooth','wireless','(Bluetooth radio ও pairing behavior যাচাই করার জন্য)','Settings → Bluetooth & devices → Add device',['Known Bluetooth device pair করুন; audio/input transfer যেখানে relevant পরীক্ষা করুন।'],'','Windows Settings','Bluetooth device discover/pair হবে যেখানে compatible।','Pairing issue driver, device, privacy বা radio-specific হতে পারে।',['Cannot detect/pair any known device হলে further inspection করুন।'])]},
{id:'ports',title:'Part 11 — Ports',tests:[
T('usb','USB-A / USB-C','ports','(প্রতিটি USB port বাস্তবে data transfer করতে পারে কি না যাচাই করার জন্য)','Known-good USB storage/input device connect করুন',['Device detect, file read এবং ছোট test write করুন; safe eject করুন।'],'','File Explorer / Device Manager','Device detect হবে এবং read/write কাজ করবে।','Port capability generation/model-specific; physical connector alone যথেষ্ট নয়।',['Intermittent disconnect বা one port dead নোট করুন।']),
T('usbc','USB-C Capability','ports','(USB-C-তে data, charging, display বা high-speed feature সত্যিই আছে কি না যাচাই করার জন্য)','Exact model specification/service manual + compatible accessories দিয়ে test করুন',['USB-C connector দেখে feature অনুমান করবেন না; specification cross-check করুন।'],'','Manufacturer specification / physical test','Supported feature অনুযায়ী behavior দেখা যাবে।','USB-C connector does not automatically mean Thunderbolt, USB4, charging or display output।',['Claimed feature না থাকলে seller-এর কাছে exact specification যাচাই করুন।']),
T('hdmi','HDMI / DisplayPort','ports','(external display output যাচাই করার জন্য)','Known-good monitor/TV ও cable ব্যবহার করুন',['Connect, select display mode এবং stable output দেখুন।'],'','Settings → System → Display','External display detect হবে যেখানে port supports it।','Port version/capability model-specific।',[]),
T('sd','SD Card','ports','(SD card reader কাজ করছে কি না যাচাই করার জন্য)','Known-good SD card insert করুন',['Detect, read a file, eject।'],'','File Explorer','Card detect হবে এবং files readable হবে।','Some models have microSD rather than full SD।',[]),
T('ethernet','Ethernet / LAN','ports','(wired network port ও link stability যাচাই করার জন্য)','Known-good Ethernet cable + network/router ব্যবহার করুন',['Connect and confirm adapter/link state; optional ipconfig /all দিয়ে address দেখুন।'],'','Settings / Command Prompt','Ethernet adapter link/connection দেখাবে।','No network access can be caused by upstream network, not necessarily port failure।',[])]},
{id:'motherboard',title:'Part 12 — Motherboard',tests:[
T('baseboard','Baseboard Information','motherboard','(motherboard manufacturer/product/version/serial evidence পাওয়ার জন্য)','System Information → BaseBoard fields',['Manufacturer, Product, Version, SerialNumber নোট করুন।'],'Get-CimInstance Win32_BaseBoard | Select-Object Manufacturer,Product,Version,SerialNumber','PowerShell','Baseboard fields দেখা যাবে।','Exact board data model/service documentation-এর সঙ্গে মিলিয়ে দেখুন।',[]),
T('device-manager','Device Manager','motherboard','(hardware driver/status warnings খুঁজে বের করার জন্য)','Run → Device Manager',['USB controllers, network, Bluetooth, audio, storage, system devices, display adapters এবং Unknown devices expand করুন।'],'devmgmt.msc','Run','Device Manager খুলবে।','Yellow warning/unknown device গুরুত্বপূর্ণ evidence, কিন্তু Device Manager alone motherboard 100% healthy প্রমাণ করে না।',['Unknown device বা repeated error status নোট করুন।']),
T('motherboard-functional','Motherboard Functional Test','motherboard','(major onboard functions একসঙ্গে বাস্তবে কাজ করছে কি না যাচাই করার জন্য)','USB, audio, network, storage, display এবং sleep/wake tests-এর ফল একত্রে দেখুন',['একটি single test নয়—সব functional checks cross-reference করুন।'],'','Combined manual inspection','Multiple onboard functions কাজ করার evidence পাওয়া যাবে।','এই workflow motherboard-এর সম্পূর্ণ health certificate নয়।',[])]},
{id:'bios',title:'Part 13 — BIOS / UEFI',tests:[
T('bios-access','BIOS / UEFI Access','bios','(firmware setup access ও lock state যাচাই করার জন্য)','Restart → manufacturer-specific BIOS/UEFI key; key model-specific documentation-এ যাচাই করুন',['Boot-এর সময় supported BIOS/UEFI key ব্যবহার করুন; universal key ধরে নেবেন না।'],'','BIOS/UEFI','BIOS/UEFI setup খুলবে যদি access available থাকে।','Manufacturer/model অনুযায়ী key ও menu আলাদা হতে পারে।',['Unknown BIOS password/lock থাকলে seller-এর মাধ্যমে resolve করুন; bypass নয়।']),
T('bios-version','BIOS Version','bios','(firmware version/date inventory-এর সঙ্গে মিলানোর জন্য)','PowerShell অথবা System Information',['BIOS version/date note করুন।'],'Get-CimInstance Win32_BIOS | Select-Object Manufacturer,SMBIOSBIOSVersion,ReleaseDate,SerialNumber','PowerShell','Manufacturer, version, release date ও serial-related fields আসবে।','Firmware update history বা latest-ness দাবি করতে exact manufacturer support page দেখুন।',[]),
T('bios-password','BIOS Password','bios','(setup password/lock state seller-এর কাছে পরিষ্কার করার জন্য)','Restart করে BIOS/UEFI access attempt করুন; password prompt হলে seller-কে জিজ্ঞাসা করুন',['Password prompt এলে কোনো bypass চেষ্টা করবেন না।'],'','BIOS/UEFI','Access state জানা যাবে।','Ownership/repair context অনুযায়ী lock resolve করা উচিত।',['BIOS password/lock unresolved থাকলে transaction-এর আগে seller clarification দরকার।'])]},
{id:'thermal',title:'Part 14 — Cooling / Fan',tests:[
T('temps','Temperature Monitoring','thermal','(CPU/GPU/SSD thermal behavior workload-এর সময় পর্যবেক্ষণের জন্য)','Task Manager basic view; optional HWiNFO for detailed sensors',['Idle এবং sustained workload-এ CPU/GPU/SSD temperature, clocks এবং throttling indicators দেখুন।'],'','Task Manager / HWiNFO','Sensors workload অনুযায়ী পরিবর্তিত হবে।','একটি universal temperature limit নেই; CPU/GPU model specifications ও symptoms-এর context দেখুন।',['Thermal throttling, shutdown, severe stutter বা abnormal fan behavior নোট করুন।']),
T('fan','Fan','thermal','(fan noise, cooling response ও abnormal behavior যাচাই করার জন্য)','Light → sustained workload দিন এবং fan response শুনুন; vents visually inspect করুন',['Blocked vents থাকলে নিজে disassemble না করে condition note করুন।'],'','Physical / workload test','Load বাড়লে fan response model অনুযায়ী পরিবর্তিত হতে পারে।','Fan RPM/curve model-specific।', ['Grinding/rattling, no cooling response বা repeated thermal shutdown নোট করুন.'])]},
{id:'physical',title:'Part 15 — Physical Body',tests:[
T('chassis','Chassis','physical','(body condition, repair marks ও structural damage যাচাই করার জন্য)','Visual inspection under good light',['Scratches, dents, cracks, screws, rubber feet, ports, bezel ও palm rest দেখুন।'],'','Physical inspection','Condition visibly documented হবে।','Cosmetic wear আলাদা করে record করুন; cosmetic issue নিজে hardware failure নয়।',[]),
T('hinge','Hinge','physical','(lid hinge stability ও chassis separation যাচাই করার জন্য)','Open/close slowly through normal range',['Uneven resistance, cracking sound, separation বা loose hinge দেখুন।'],'','Physical inspection','Hinge smooth and stable হওয়া উচিত।','Hinge tension model-specific।',['Loose hinge, crack বা chassis separation সতর্কতার বিষয়।']),
T('liquid','Liquid / Corrosion','physical','(liquid damage বা corrosion-এর visual signs শনাক্ত করার জন্য)','Ports, screws, seams, keyboard area ও accessible indicators visually inspect করুন',['Laptop খুলবেন না যদি তা আপনার দক্ষতা/ownership scope-এর বাইরে হয়; visible evidence record করুন।'],'','Physical inspection','Visible corrosion/liquid residue থাকা উচিত নয়।','Internal condition নিশ্চিত করতে qualified inspection লাগতে পারে।',['Corrosion, residue বা liquid indicator evidence নোট করুন।'])]},
{id:'windows',title:'Part 16 — Windows Activation & Security',tests:[
T('activation','Windows Activation','windows','(Windows activation state seller claim ও installed edition-এর সঙ্গে মিলানোর জন্য)','Settings → System → Activation',['Activation status ও edition নোট করুন।'],'slmgr /xpr','Command Prompt','Windows activation expiry/notification dialog দেখাবে।','Genuine activation status-এর evidence হিসেবে multiple sources মিলিয়ে দেখুন।',['Unexpected activation state হলে seller-এর কাছে clarification নিন।']),
T('windows-update','Windows Update','windows','(pending updates ও update state বোঝার জন্য)','Settings → Windows Update',['Check for updates; pending restart/update note করুন।'],'','Settings','Current update state দেখাবে।','Update availability time-sensitive; pending update নিজে hardware defect নয়।',[]),
T('local-users','Local User Accounts','windows','(existing local accounts সম্পর্কে basic inventory দেখার জন্য)','Settings → Accounts; Command Prompt','net user','Command Prompt','Local user names list হবে।','Unknown account থাকলে seller-এর সঙ্গে ownership/privacy context যাচাই করুন।',['Unexpected account থাকলে clarification দরকার।']),
T('admin-accounts','Administrator Accounts','windows','(administrator group membership যাচাই করার জন্য)','Computer Management → Local Users and Groups where available; PowerShell',['Administrators group members record করুন।'],'Get-LocalGroupMember -Group "Administrators"','PowerShell','Administrator group members list হবে।','Windows edition/features অনুযায়ী GUI path কিছুটা ভিন্ন হতে পারে।',['Unknown administrator membership থাকলে seller-এর কাছে explanation নিন।']),
T('organization','Organization Enrollment','windows','(company/school management enrollment আছে কি না যাচাই করার জন্য)','Settings → Accounts → Access work or school; Command Prompt/PowerShell',['Connected organization accounts/status inspect করুন।'],'dsregcmd /status','Command Prompt','Device join/registration state fields দেখা যাবে।','Organization enrollment/management ownership issue হলে seller-এর মাধ্যমে resolve করুন; bypass করবেন না।',['Organization enrollment/management unexpectedly present হলে critical attention।'])]},
{id:'events',title:'Part 17 — Event Viewer',tests:[T('event-log','System Error Log','events','(repeated disk, controller, driver বা shutdown errors-এর evidence দেখতে)','Run → Event Viewer → Windows Logs → System',['Repeated recent errors-এর source, Event ID, date/time এবং frequency note করুন।'],'eventvwr.msc','Run','Event Viewer খুলবে।','একটি isolated old event নিজে hardware failure প্রমাণ করে না; pattern ও recurrence দেখুন।',['Repeated disk/controller/driver errors বা unexpected shutdown pattern নোট করুন।'])]},
{id:'stability',title:'Part 18 — Stability',tests:[
T('cold-boot','Cold Boot','stability','(পূর্ণ shutdown-এর পর clean boot stability যাচাই করার জন্য)','Shut down completely, then power on',['Boot time, errors, display, audio, network ও responsiveness observe করুন।'],'','Power menu','Normal boot sequence expected।','Cold boot এবং restart আলাদা behavior দেখাতে পারে।',['Boot failure, repeated repair screen বা abnormal shutdown নোট করুন।']),
T('restart','Restart','stability','(restart cycle stability যাচাই করার জন্য)','Start → Power → Restart',['Restart complete হওয়া এবং hardware functions ফিরে আসা দেখুন।'],'','Windows','System should restart normally।','One failed restart may need context; repeated failure matters more।',['Repeated restart failure বা crash নোট করুন।']),
T('sleep-wake','Sleep / Wake','stability','(sleep থেকে wake-এর পর display, Wi-Fi, audio ও input recovery যাচাই করার জন্য)','Start → Power → Sleep → wake device',['Display, Wi-Fi, audio, touchpad/keyboard এবং USB state দেখুন।'],'','Windows','Supported sleep state থেকে wake করলে core functions ফিরে আসবে।','Modern Standby behavior model-specific হতে পারে।',['Black screen, lost Wi-Fi/audio বা repeated wake failure নোট করুন।'])]},
{id:'power',title:'Part 19 — Power Diagnostics',tests:[
T('energy','Energy Report','power','(Windows power-management diagnostics থেকে evidence পাওয়ার জন্য)','Admin Command Prompt খুলে report চালান; কাজ শেষে generated HTML report পড়ুন',['Report path খুলে warnings/errors দেখুন।'],'powercfg /energy','Administrator Command Prompt','energy-report.html তৈরি হবে এবং report path দেখাবে।','এটি diagnostic report, health certificate নয়।',[], 'Windows 10/11', 'Power settings/driver warnings context সহ নোট করুন।',true),
T('sleep-states','Supported Sleep States','power','(কোন sleep states firmware/Windows support করে বোঝার জন্য)','Command Prompt খুলে supported states দেখুন',['Available and unavailable sleep states note করুন।'],'powercfg /a','Command Prompt','Supported/unavailable sleep states এবং reasons দেখা যাবে।','Hardware/firmware configuration অনুযায়ী states ভিন্ন হতে পারে।',[])]},
{id:'inventory',title:'Part 20 — Hardware Inventory',tests:[
T('cpu-inventory','CPU Inventory','inventory','(hardware inventory record তৈরি করার জন্য)','PowerShell',['CPU model/core/thread values save করুন।'],'Get-CimInstance Win32_Processor | Select-Object Name,Manufacturer,NumberOfCores,NumberOfLogicalProcessors,MaxClockSpeed','PowerShell','CPU inventory fields দেখা যাবে।','Inventory data seller claim ও system information-এর সঙ্গে cross-check করুন.',[]),
T('ram-inventory','RAM Inventory','inventory','(প্রতিটি memory module-এর record রাখার জন্য)','PowerShell',['Manufacturer, part number, capacity, speed, device locator নোট করুন।'],'Get-CimInstance Win32_PhysicalMemory | Select-Object Manufacturer,PartNumber,Capacity,Speed,ConfiguredClockSpeed,DeviceLocator','PowerShell','Module-level inventory fields দেখা যাবে।','Total capacity যোগ করে cross-check করুন.',[]),
T('bios-inventory','BIOS Inventory','inventory','(firmware identity record রাখার জন্য)','PowerShell',['Manufacturer, SMBIOSBIOSVersion, ReleaseDate, SerialNumber নোট করুন।'],'Get-CimInstance Win32_BIOS | Select-Object Manufacturer,SMBIOSBIOSVersion,ReleaseDate,SerialNumber','PowerShell','BIOS inventory fields দেখা যাবে।','Exact model support documentation-এর সঙ্গে মিলিয়ে দেখুন.',[]),
T('board-inventory','Motherboard Inventory','inventory','(baseboard identity record রাখার জন্য)','PowerShell',['Manufacturer, Product, Version, SerialNumber নোট করুন।'],'Get-CimInstance Win32_BaseBoard | Select-Object Manufacturer,Product,Version,SerialNumber','PowerShell','Baseboard inventory fields দেখা যাবে।','Board information firmware/OS reporting-এর উপর নির্ভর করতে পারে.',[])]},
{id:'upgrade',title:'Part 21 — Upgrade Compatibility',tests:[
T('upgrade-ram','RAM Upgrade','upgrade','(future RAM expansion বাস্তবে সম্ভব কি না যাচাই করার জন্য)','Exact model/service manual + current RAM inventory',['Slot count, soldered memory এবং maximum supported RAM verify করুন।'],'','Manufacturer documentation','Supported configuration জানা যাবে।','Exact model ছাড়া compatibility guess করবেন না।',['No free slot বা soldered-only design হলে expansion সীমিত হতে পারে।']),
T('upgrade-ssd','SSD Upgrade','upgrade','(storage replacement/expansion interface ও physical compatibility যাচাই করার জন্য)','Exact model/service manual + current Disk/Device Manager',['M.2 size/interface, bay availability, maximum supported configuration verify করুন।'],'','Manufacturer documentation','Supported storage configuration জানা যাবে।','M.2 connector-এর shape দেখে NVMe/SATA support ধরে নেবেন না।',['No bay বা unsupported interface হলে upgrade সীমিত।']),
T('upgrade-usbc','USB-C Feature Compatibility','upgrade','(USB-C feature set ভবিষ্যৎ use-case-এর জন্য যথেষ্ট কি না যাচাই করার জন্য)','Exact manufacturer specification/service manual',['Data speed, charging input/output, display Alt Mode, Thunderbolt/USB4 যেখানে applicable verify করুন।'],'','Manufacturer documentation','Exact feature support জানা যাবে।','Connector shape is not feature specification।',[]),
T('upgrade-wireless','Wi-Fi / Bluetooth Upgrade','upgrade','(wireless module replaceable ও compatible কি না যাচাই করার জন্য)','Service manual + current Device Manager inventory',['Module form factor, interface, antenna compatibility এবং OS driver support verify করুন।'],'','Manufacturer documentation','Supported module/upgrade information পাওয়া যাবে।','Regulatory/whitelist constraints may apply to some models।',[])]},
{id:'new',title:'Part 22 — New Laptop',tests:[
T('box-serial','Box / Serial Verification','new','(নতুন laptop-এর box, device এবং documentation একই unit কি না cross-check করার জন্য)','Box label, laptop label/BIOS/Windows information এবং invoice compare করুন',['Serial/model fields carefully compare করুন; publicভাবে serial share করবেন না।'],'','Physical + System Information','Relevant identifiers consistent হওয়া উচিত।','Manufacturing/retail process অনুযায়ী label location varies।',['Mismatch হলে seller explanation চাইুন।']),
T('warranty','Warranty Verification','new','(warranty claim বাস্তব manufacturer record-এর সঙ্গে মিলানোর জন্য)','Manufacturer official warranty lookup যেখানে available',['Model/serial দিয়ে official warranty status verify করুন; screenshot/private serial share করবেন না।'],'','Manufacturer official website','Warranty coverage/term দেখা যেতে পারে।','Warranty database availability varies by manufacturer/region।',['Warranty status mismatch হলে seller-এর কাছে documentation চান।']),
T('factory-config','Factory Configuration','new','(invoice/advertised configuration এবং actual factory configuration মিলানোর জন্য)','Invoice + system inventory + physical labels',['CPU, RAM, SSD, GPU, display model where available cross-check করুন।'],'','Cross-check','Multiple sources aligned হওয়া উচিত।','Upgrades/replacements থাকলে seller should disclose them।',[])]},
{id:'used',title:'Part 23 — Used Laptop',tests:[
T('repair-history','Repair History','used','(আগের repair/replacement সম্পর্কে seller disclosure যাচাই করার জন্য)','Seller interview + invoice/service records where available',['Motherboard, display, battery, SSD, keyboard, liquid damage এবং warranty repair history জিজ্ঞাসা করুন।'],'','Seller / service documentation','Seller-এর documented answer record করুন।','Unverified verbal claim-কে fact হিসেবে treat করবেন না।',['Repair history unknown বা conflicting হলে note করুন।']),
T('parts-mismatch','Parts Mismatch','used','(installed parts advertised specification থেকে বদলেছে কি না বুঝতে)','System inventory + physical labels + seller claim compare করুন',['CPU/RAM/SSD/GPU/display/battery/charger claims side-by-side compare করুন।'],'','Cross-check','Observed and claimed data can be recorded separately।','Mismatch does not automatically prove fraud; ask for reason/documentation।',['Unexplained mismatch = attention item'])]}
];
const quickSequence=[['00–05','Identity',['system-info','cpu-info']],['05–10','Physical',['chassis','hinge','liquid']],['10–15','Display',['display-mode','dead-pixel','screen-angle','brightness']],['15–20','Input / Audio / Camera',['keyboard','touchpad','speaker','microphone','webcam']],['20–25','Ports / Wireless',['usb','usbc','wifi','bluetooth']],['25–30','SSD + Battery',['storage-info','physical-disk','battery-report']],['30–40','CPU / GPU / Temperature',['cpu-load','gpu-info','gpu-stress','temps','fan']],['40–45','BIOS / Windows / Stability',['bios-access','bios-version','bios-password','activation','organization','cold-boot','restart','sleep-wake']]];
const masterCommands=[
['msinfo32','System Information','Run / Start Search','Windows 10/11','System manufacturer/model, BIOS, RAM, baseboard fields.'],['dxdiag','DirectX/GPU diagnostic information','Run / Command Prompt','Windows 10/11','DirectX Diagnostic Tool opens.'],['devmgmt.msc','Device Manager','Run','Windows 10/11','Hardware categories and device status.'],['powercfg /batteryreport','Battery report','Command Prompt','Windows 10/11','Creates battery-report.html.'],['powercfg /energy','Energy report','Administrator Command Prompt','Windows 10/11','Creates energy-report.html; admin may be required.'],['powercfg /a','Supported sleep states','Command Prompt','Windows 10/11','Lists available/unavailable sleep states.'],['ipconfig /all','Network adapter configuration','Command Prompt','Windows 10/11','Adapter/IP/DHCP/DNS information.'],['netsh wlan show interfaces','Wi-Fi interface status','Command Prompt','Windows 10/11','Wi-Fi interface, SSID, radio and signal details.'],['mdsched.exe','Windows Memory Diagnostic','Run / Start Search','Windows 10/11','Schedules memory diagnostic on restart.'],['eventvwr.msc','Event Viewer','Run','Windows 10/11','Windows event logs.'],['slmgr /xpr','Activation expiry/status dialog','Command Prompt','Windows 10/11','Activation status dialog.'],['slmgr /dlv','Detailed licensing information','Command Prompt','Windows 10/11','Detailed license channel/status dialog.'],['net user','Local user list','Command Prompt','Windows 10/11','Local user account names.'],['dsregcmd /status','Device join/registration status','Command Prompt','Windows 10/11','Work/school/Azure AD-related registration fields.']];
const powershellCommands=[
['Get-CimInstance Win32_Processor | Select-Object Name,Manufacturer,NumberOfCores,NumberOfLogicalProcessors,MaxClockSpeed','CPU inventory'],['Get-CimInstance Win32_PhysicalMemory | Select-Object Manufacturer,PartNumber,Capacity,Speed,ConfiguredClockSpeed,DeviceLocator','RAM inventory'],['Get-CimInstance Win32_BIOS | Select-Object Manufacturer,SMBIOSBIOSVersion,ReleaseDate,SerialNumber','BIOS inventory'],['Get-CimInstance Win32_BaseBoard | Select-Object Manufacturer,Product,Version,SerialNumber','Motherboard inventory'],['Get-CimInstance Win32_Battery','Battery WMI information'],['Get-Disk | Format-Table Number,FriendlyName,SerialNumber,BusType,HealthStatus,OperationalStatus,Size','Disk inventory/status'],['Get-PhysicalDisk | Format-Table FriendlyName,MediaType,BusType,HealthStatus,OperationalStatus,Size','Physical disk health/status'],['Get-LocalGroupMember -Group "Administrators"','Administrator group members'],['Get-ComputerInfo','Broad Windows/system inventory']];
const allTests=inspectionSections.flatMap(s=>s.tests.map(t=>({...t,category:s.title})));

const KEY='ulg-meemo-state-v1';
const defaults={theme:'system',statuses:{},notes:{},claims:{},currentTest:null,quickStarted:null,updatedAt:null};
function loadState(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}}
function saveState(state){state.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){/* localStorage may be restricted for file:// */}}
function resetState(){try{localStorage.removeItem(KEY)}catch(e){} return {...defaults}}
function setTheme(theme){const s=loadState();s.theme=theme;saveState(s)}

const $=(s,root=document)=>root.querySelector(s);
const $$=(s,root=document)=>[...root.querySelectorAll(s)];
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();let ok=false;try{ok=document.execCommand('copy')}catch{}ta.remove();return ok}}
function greeting(){const h=new Date().getHours();if(h>=5&&h<12)return 'শুভ সকাল!';if(h>=12&&h<18)return 'শুভ বিকেল!';if(h>=18&&h<23)return 'শুভ সন্ধ্যা!';return 'শুভ রাত্রি!'}
function statusLabel(s){return ({checked:'✓ Checked',warning:'⚠ Warning',problem:'! Problem Found',more:'? Need More Inspection',skipped:'— Skipped',none:'Not Checked'})[s||'none']}
function normalize(s){return String(s||'').toLowerCase()}

const meemoMessages={
 identity:'চলো শুরু করি। প্রথমে laptop-এর আসল model ও configuration seller-এর কথার সঙ্গে মিলিয়ে দেখি।',
 cpu:'এবার CPU পরীক্ষা করি। নাম, core এবং logical processor তথ্য নোট করে রাখো।',
 gpu:'GPU-তে এবার model, driver এবং load-এর আচরণ দেখো। কোনো artifact বা crash হলে নোট করো।',
 ram:'RAM-এর capacity ও speed দেখার পাশাপাশি error test এবং upgradeability-ও যাচাই করি।',
 storage:'Storage শুধু capacity নয়—health, interface এবং performance-এর তথ্যও মিলিয়ে দেখব।',
 display:'এখন screen-এর solid colors দেখে pixel, line, flicker এবং brightness-এর সমস্যা খুঁজি।',
 battery:'Battery percentage একা যথেষ্ট নয়। Design Capacity ও Full Charge Capacity-এর তথ্যও দেখি।',
 ports:'প্রতিটি port বাস্তবে device দিয়ে পরীক্ষা করো। USB-C দেখলেই সব feature আছে ধরে নিও না।',
 windows:'Windows activation, update ও organization status দেখে laptop-এর software অবস্থাটা বুঝি।',
 physical:'এখন body, hinge, screws, ports এবং liquid/corrosion-এর চিহ্ন মন দিয়ে দেখো।',
 default:'চলো ধাপে ধাপে এগোই। যা দেখবে, সেটাই নোট করো—অনুমান নয়, evidence সংগ্রহ করাই লক্ষ্য।'
};
function meemoKey(test){const t=(test?.title||'').toLowerCase();for(const k of Object.keys(meemoMessages)){if(t.includes(k))return k}return test?.sectionKey||'default'}
function setMeemoState(el,state='idle'){if(!el)return;el.dataset.state=state}

function meemoSvg(){return `<div class="meemo-mini"><img src="assets/meemo.svg" alt="Meemo cat assistant"></div>`}
function renderTestCard(t,state){const st=state.statuses[t.id]||'none';return `<article class="test-card" data-test-card data-id="${esc(t.id)}" data-search="${esc([t.title,t.purpose,t.category,t.gui,t.command,t.expected,t.interpretation].join(' '))}"><div class="test-meta"><span class="pill">#${esc(t.id)}</span><span class="pill">${esc(t.platform)}</span>${t.admin?'<span class="pill">Admin may be required</span>':''}</div><h3>${esc(t.title)}</h3><p class="why">${esc(t.purpose)}</p><div class="meemo-line">${meemoSvg()}<div><strong>Meemo:</strong> ${esc(t.meemo||'চলো ধাপে ধাপে evidence সংগ্রহ করি।')}</div></div><div class="step-grid"><div class="subpanel"><h4>GUI method</h4><p>${esc(t.gui)}</p><h4>How to run / Where</h4><p>${esc(t.where)}</p><ol class="steps">${t.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div><div class="subpanel"><h4>Command method</h4>${t.command?`<div class="code-wrap"><pre class="code"><code>${esc(t.command)}</code></pre><button class="copy-btn" type="button" data-copy="${esc(t.command)}">Copy</button></div>`:'<p class="muted">এই test-এর জন্য command দরকার নেই; GUI/physical method ব্যবহার করুন।</p>'}<h4>What to look for</h4><p>${esc(t.expected)}</p></div></div><div class="grid-2" style="margin-top:12px"><div class="subpanel"><h4>✓ স্বাভাবিক / Good result</h4><p>${esc(t.expected)}</p></div><div class="subpanel"><h4>Interpretation</h4><p>${esc(t.interpretation)}</p></div></div>${t.warnings.length?`<div class="alert" style="margin-top:12px"><strong>⚠ সতর্ক:</strong><ul>${t.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></div>`:''}<p><strong>Next Step:</strong> ${esc(t.next)}</p><div class="status-row" role="group" aria-label="${esc(t.title)} status">${[['checked','✓ Checked'],['warning','⚠ Warning'],['problem','! Problem Found'],['more','? Need More Inspection'],['skipped','— Skipped']].map(([k,l])=>`<button type="button" class="status-btn ${st===k?'active':''}" data-status="${k}" data-test="${esc(t.id)}">${l}</button>`).join('')}</div><label><span class="sr-only">${esc(t.title)} notes</span><textarea class="notes" data-note="${esc(t.id)}" placeholder="My Notes — যেমন: Battery 82%, seller says recently replaced.">${esc(state.notes[t.id]||'')}</textarea></label><div class="card-footer"><span class="pill">Status: ${esc(statusLabel(st))}</span><button class="btn ghost next-test" type="button" data-next="${esc(t.id)}">Mark & Continue →</button></div></article>`}
function renderCommandCard(cmd,idx,ps=false){const [command,purpose,where='PowerShell'] = cmd; const label=ps?purpose:cmd[1];return `<article class="panel command-card"><div class="test-meta"><span class="pill">${ps?'PowerShell':'Command'} #${idx+1}</span><span class="pill">Windows 10/11</span></div><h3>${esc(label)}</h3><p>${ps?'Purpose: '+esc(purpose):'Purpose: '+esc(purpose)}</p><p class="muted">Where: ${esc(where)}</p><div class="code-wrap"><pre class="code"><code>${esc(command)}</code></pre><button class="copy-btn" type="button" data-copy="${esc(command)}">Copy</button></div><p><strong>Expected:</strong> ${esc(ps?'Relevant inventory output appears.':cmd[4])}</p><p><strong>Interpretation:</strong> Information-gathering output; compare it with seller claims and exact model documentation.</p></article>`}

let state=loadState();
allTests.forEach(t=>{t.meemo=meemoMessages[meemoKey(t)]||meemoMessages.default});
const app=$('#app');
const total=allTests.length;
function applyTheme(){document.body.classList.toggle('dark',state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches))}
applyTheme();
function counts(){const vals=Object.values(state.statuses);return {checked:vals.filter(x=>x==='checked').length,warning:vals.filter(x=>x==='warning').length,problem:vals.filter(x=>x==='problem').length,more:vals.filter(x=>x==='more').length,skipped:vals.filter(x=>x==='skipped').length,done:vals.filter(x=>x&&x!=='none').length}}
function shell(title,subtitle,body){return `<div class="page"><div class="section-head"><div><div class="eyebrow">MEEEMO • INSPECTION ASSISTANT</div><h2>${esc(title)}</h2><p class="muted">${esc(subtitle)}</p></div></div>${body}</div>`}
function home(){return `<section class="hero" id="home"><div><span class="eyebrow">${esc(greeting())} • Windows 10/11</span><h1>Used Laptop Buying Guidelines</h1><p>Used Laptop কেনার আগে — দেখুন, পরীক্ষা করুন, তারপর সিদ্ধান্ত নিন।</p><p><strong>আমি Meemo — তোমার Laptop Checking Buddy!</strong><br>আমি তোমাকে CPU, RAM, GPU, SSD/HDD, Battery, Display, Keyboard, Touchpad, Camera, Microphone, Speakers, Wi-Fi, Bluetooth, USB, HDMI, Charger, Thermal behavior, Windows, BIOS/UEFI এবং physical condition ধাপে ধাপে পরীক্ষা করতে সাহায্য করব।</p><div class="hero-actions"><a class="btn primary" href="#dashboard">START TEST MY LAPTOP!</a><a class="btn" href="#quick">Quick Inspection</a></div><div class="feature-grid">${['Objective evidence','Windows 10 + 11','LocalStorage progress','No automatic commands','GUI + command methods','নিজের সিদ্ধান্ত নিজেই'].map(x=>`<div class="feature">✓ ${esc(x)}</div>`).join('')}</div></div><div class="meemo-stage"><div class="meemo-wrap"><img src="assets/meemo.svg" alt="Meemo animated cat assistant"></div></div></section><div class="page"><div class="grid-2"><div class="panel"><h2>কেন এই website?</h2><p>Seller-এর দাবি আর laptop-এর বাস্তব configuration সবসময় একই নাও হতে পারে। তাই এখানে structured workflow দিয়ে evidence সংগ্রহ করা হয়।</p><p><strong>দেখুন → পরীক্ষা করুন → তথ্য মিলিয়ে দেখুন → বুঝুন → তারপর নিজের সিদ্ধান্ত নিন।</strong></p></div><div class="panel"><h2>Safety first</h2><p>Information-gathering command-কে অগ্রাধিকার দিন। কোনো system-changing command না বুঝে চালাবেন না। Battery swelling সন্দেহ হলে নিজে battery খুলবেন না। BIOS বা organization lock bypass করার নির্দেশনা এই guide দেয় না।</p></div></div></div>`}
function dashboard(){const c=counts(),pct=Math.round(c.done/total*100);return shell('Inspection Dashboard','Laptop সামনে রেখে step-by-step inspection চালাও।',`<div class="panel"><div class="stat-grid"><div class="stat"><strong>${c.done} / ${total}</strong>Tests Completed</div><div class="stat"><strong>${c.checked}</strong>Checked</div><div class="stat"><strong>${c.warning}</strong>Warnings</div><div class="stat"><strong>${c.problem}</strong>Problems</div><div class="stat"><strong>${c.more+c.skipped}</strong>Need / Skipped</div></div><div style="margin-top:15px"><div class="progress" aria-label="Inspection progress"><span style="width:${pct}%"></span></div><p><strong>Inspection Progress: ${pct}%</strong></p></div></div><div class="grid-3" style="margin-top:18px"><a class="panel" href="#tests"><h3>All Tests</h3><p>সব ${total}টি inspection item একসঙ্গে দেখুন।</p></a><a class="panel" href="#quick"><h3>Quick Inspection</h3><p>30–45 মিনিটের focused sequence চালান।</p></a><a class="panel" href="#summary"><h3>Final Summary</h3><p>সংগৃহীত evidence, warning ও অসম্পূর্ণ test দেখুন।</p></a></div><div class="panel" style="margin-top:18px"><h3>Reset Inspection</h3><p>সব status, notes ও seller claims মুছে নতুন inspection শুরু করবে।</p><button class="btn danger" id="resetBtn">Reset Inspection</button></div>`)}
function tests(){return shell('All Tests','Search, filter, expand/collapse করে পুরো inspection database ব্যবহার করুন.',`<div class="panel"><div class="toolbar"><input id="search" class="search" type="search" placeholder="Search: battery, SSD, USB, BIOS, RAM, Wi-Fi…" aria-label="Search tests"><select id="filter" class="select"><option value="all">All</option><option value="none">Not Checked</option><option value="checked">Checked</option><option value="warning">Warning</option><option value="problem">Problem</option><option value="more">Need More Inspection</option><option value="skipped">Skipped</option></select><button class="btn" id="expandAll">Expand All</button><button class="btn" id="collapseAll">Collapse All</button></div></div><div id="testDatabase">${inspectionSections.map(s=>`<details class="category" open><summary>${esc(s.title)} <span class="muted">(${s.tests.length} tests)</span></summary><div class="test-list">${s.tests.map(t=>renderTestCard(t,state)).join('')}</div></details>`).join('')}</div>`)}
function quick(){return shell('30–45 Minute Quick Inspection Mode','Focused sequence — timer is only a guide and never executes any system operation.',`<div class="panel"><div class="timer" id="timer">45:00</div><div class="toolbar" style="justify-content:center"><button class="btn primary" id="startTimer">Start Timer</button><button class="btn" id="pauseTimer">Pause</button><button class="btn" id="resetTimer">Reset</button></div></div><div class="quick-steps" style="margin-top:18px">${quickSequence.map(([time,title,ids])=>`<div class="quick-step"><strong>${time}</strong><h3>${esc(title)}</h3><p>${ids.map(id=>{const t=allTests.find(x=>x.id===id);return t?`• ${esc(t.title)}`:''}).join('<br>')}</p><a class="btn" href="#tests">Open Tests</a></div>`).join('')}</div><div class="panel" style="margin-top:18px"><h3>Quick-mode principle</h3><p>এটি full inspection-এর replacement নয়। সময় কম হলে highest-value evidence আগে সংগ্রহ করতে সাহায্য করে।</p></div>`)}
function commands(){return shell('MASTER COMMAND SHEET','Information-gathering Windows commands. JavaScript কখনো command execute করবে না.',`<div class="command-list">${masterCommands.map((x,i)=>renderCommandCard(x,i)).join('')}</div>`)}
function powershell(){return shell('MASTER POWERSHELL SHEET','PowerShell inventory commands — copy করে manually run করুন।',`<div class="command-list">${powershellCommands.map((x,i)=>renderCommandCard(x,i,true)).join('')}</div><div class="panel" style="margin-top:18px"><strong>Note:</strong> Output build, edition ও hardware অনুযায়ী কিছুটা ভিন্ন হতে পারে।</div>`)}
function seller(){const fields=['CPU','RAM','SSD','GPU','Display','Battery','Model','Charger'];return shell('Seller Claim Verification','Seller-এর বক্তব্য এবং observed result পাশাপাশি record করুন। Mismatch automatically fraud প্রমাণ করে না.',`<div class="panel"><div class="table-wrap"><table class="claim-table"><thead><tr><th>Item</th><th>Seller says</th><th>Actual result</th><th>Status</th></tr></thead><tbody>${fields.map(k=>`<tr><td>${k}</td><td><input data-claim="${k}:seller" value="${esc(state.claims[k+':seller']||'')}"></td><td><input data-claim="${k}:actual" value="${esc(state.claims[k+':actual']||'')}"></td><td><select class="select" data-claim-status="${k}"><option>Not checked</option><option>Matched</option><option>Difference found</option><option>Needs clarification</option></select></td></tr>`).join('')}</tbody></table></div><p class="alert" style="margin-top:15px">Seller-এর তথ্য এবং laptop-এর বর্তমান তথ্যের মধ্যে পার্থক্য পাওয়া গেলে কারণটি seller-এর কাছে যাচাই করুন।</p></div>`)}

function currentLaptop(){return shell('Check My Current Laptop','একই inspection system ব্যবহার করে নিজের বর্তমান laptop-এর objective information record করুন।',`<div class="grid-2"><div class="panel"><h3>What this mode records</h3><ul><li>CPU / RAM / GPU / Storage</li><li>Battery and Windows status</li><li>Hardware warnings</li><li>Upgradeability evidence</li><li>Your manual notes</li></ul></div><div class="panel"><h3>How to use</h3><p>All Tests থেকে relevant items complete করুন। কোনো arbitrary overall score বা automatic health verdict দেওয়া হয় না।</p><a class="btn primary" href="#tests">Open All Tests</a></div></div><div class="panel" style="margin-top:18px"><h3>Current laptop checklist</h3><p>Dashboard-এর progress, warnings, problems, skipped items এবং Final Summary ব্যবহার করে নিজের device-এর evidence-based record তৈরি করুন।</p></div>`)}

function summary(){const c=counts();const critical=allTests.filter(t=>state.statuses[t.id]==='problem'||state.statuses[t.id]==='warning');const missing=allTests.filter(t=>!state.statuses[t.id]);return shell('Final Inspection Summary','Collected evidence-এর summary; কোনো purchase verdict নয়.',`<div class="summary-grid"><div class="status-box"><strong>${c.done}</strong><br>Completed</div><div class="status-box"><strong>${c.warning}</strong><br>Warnings</div><div class="status-box"><strong>${c.problem}</strong><br>Problems</div><div class="status-box"><strong>${c.skipped}</strong><br>Skipped</div></div><div class="grid-2" style="margin-top:18px"><div class="panel"><h3>Important attention items</h3>${critical.length?`<ul>${critical.map(t=>`<li><strong>${esc(t.title)}</strong> — ${esc(statusLabel(state.statuses[t.id]))}</li>`).join('')}</ul>`:'<p>এখন পর্যন্ত Warning/Problem status manually mark করা হয়নি।</p>'}</div><div class="panel"><h3>Incomplete tests</h3>${missing.length?`<ul>${missing.slice(0,25).map(t=>`<li>${esc(t.title)}</li>`).join('')}</ul>${missing.length>25?`<p>আরও ${missing.length-25}টি অসম্পূর্ণ।</p>`:''}`:'<p>সব test-এ status দেওয়া হয়েছে।</p>'}</div></div><div class="panel" style="margin-top:18px"><h3>System / Hardware / Verification</h3><p>CPU, RAM, GPU, Storage, Windows, Battery, Display, Keyboard, Touchpad, Camera, Microphone, Speakers, Ports, Wi-Fi, Bluetooth, Charger, Physical condition এবং seller claims-এর evidence এই inspection-এর মাধ্যমে record করা যায়।</p><p><strong>কোনো গুরুত্বপূর্ণ test অসম্পূর্ণ থাকলে সেটি আগে সম্পন্ন করুন। তারপর সংগৃহীত তথ্যের ভিত্তিতে নিজের সিদ্ধান্ত নিন।</strong></p><button class="btn primary" id="printReport">Export Inspection Report</button></div>`)}
function simple(title,body){return shell(title,title==='Safety'?'নিরাপদ, evidence-based inspection workflow.':'Meemo তোমাকে inspect করতে সাহায্য করে—decision তোমার.',`<div class="panel">${body}</div>`)}
function route(){const r=location.hash.replace('#','')||'home';let html=r==='home'?home():r==='dashboard'?dashboard():r==='tests'?tests():r==='quick'?quick():r==='commands'?commands():r==='powershell'?powershell():r==='seller'?seller():r==='current'?currentLaptop():r==='summary'?summary():r==='safety'?simple('Safety',`<h3>Safety Notice</h3><p>কোনো command চালানোর আগে নির্দেশনা পড়ুন। Information-gathering command-কে অগ্রাধিকার দিন। Administrator command-এর ক্ষেত্রে বিশেষ সতর্ক থাকুন। কোনো system-changing command না বুঝে চালাবেন না।</p><p><strong>Battery swelling:</strong> নিজে battery খুলে পরীক্ষা করবেন না।</p><p><strong>BIOS/Organization lock:</strong> seller/authorized support-এর মাধ্যমে resolve করুন; bypass instructions ব্যবহার করবেন না।</p>`):simple('About Meemo',`<div class="meemo-line">${meemoSvg()}<div><h3>আমি Meemo — তোমার Laptop Checking Buddy!</h3><p>আমি friendly inspection guide। আমি evidence সংগ্রহে সাহায্য করি, কিন্তু laptop কিনবে কি না সেই সিদ্ধান্ত আমি নিই না।</p></div></div>`);app.innerHTML=html;window.scrollTo({top:0,behavior:'smooth'});bind();}
function bind(){
  $$('#testDatabase [data-copy], .command-card [data-copy]').forEach(b=>b.addEventListener('click',async()=>{const ok=await copyText(b.dataset.copy);b.textContent=ok?'কপি হয়েছে':'Copy failed';setTimeout(()=>b.textContent='Copy',1300)}));
  $$('[data-status]').forEach(b=>b.addEventListener('click',()=>{state.statuses[b.dataset.test]=b.dataset.status;state.currentTest=b.dataset.test;saveState(state);route()}));
  $$('[data-next]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.next;state.statuses[id]='checked';state.currentTest=id;saveState(state);const i=allTests.findIndex(t=>t.id===id);const next=allTests[i+1];if(next){location.hash='#tests';setTimeout(()=>{const el=document.querySelector(`[data-id=\"${CSS.escape(next.id)}\"]`);el?.scrollIntoView({behavior:'smooth',block:'center'});},60)}else{location.hash='#summary'}}));
  $$('[data-note]').forEach(n=>n.addEventListener('input',()=>{state.notes[n.dataset.note]=n.value;saveState(state)}));
  $$('#search').forEach(el=>el.addEventListener('input',filterTests));$$('#filter').forEach(el=>el.addEventListener('change',filterTests));
  $('#expandAll')?.addEventListener('click',()=>$$('.category').forEach(x=>x.open=true));$('#collapseAll')?.addEventListener('click',()=>$$('.category').forEach(x=>x.open=false));
  $('#resetBtn')?.addEventListener('click',()=>{if(confirm('সব inspection status এবং notes মুছে ফেলতে চান?')){state=resetState();applyTheme();route()}});
  $$('[data-claim]').forEach(i=>i.addEventListener('input',()=>{state.claims[i.dataset.claim]=i.value;saveState(state)}));
  $$('[data-claim-status]').forEach(s=>{const key=s.dataset.claimStatus;s.value=state.claims[key+':status']||'Not checked';s.addEventListener('change',()=>{state.claims[key+':status']=s.value;saveState(state)})});
  $('#printReport')?.addEventListener('click',()=>window.print());
  bindTimer();
}
function filterTests(){const q=normalize($('#search')?.value),f=$('#filter')?.value||'all';$$('[data-test-card]').forEach(card=>{const t=allTests.find(x=>x.id===card.dataset.id);const okQ=!q||normalize(card.dataset.search).includes(q);const okF=f==='all'||(state.statuses[t.id]||'none')===f;card.hidden=!(okQ&&okF)});$$('.category').forEach(c=>{c.hidden=!c.querySelector('[data-test-card]:not([hidden])')})}
let timerId=null,remaining=2700;
function bindTimer(){const out=$('#timer');if(!out)return;const render=()=>out.textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;render();$('#startTimer')?.addEventListener('click',()=>{if(timerId)return;timerId=setInterval(()=>{if(remaining>0){remaining--;render()}else{clearInterval(timerId);timerId=null}},1000)});$('#pauseTimer')?.addEventListener('click',()=>{clearInterval(timerId);timerId=null});$('#resetTimer')?.addEventListener('click',()=>{clearInterval(timerId);timerId=null;remaining=2700;render()})}
$('#themeBtn')?.addEventListener('click',()=>{
  state.theme = state.theme==='light' ? 'dark' : state.theme==='dark' ? 'system' : 'light';
  saveState(state); applyTheme();
  const b=$('#themeBtn'); if(b) b.title='Theme: '+state.theme;
});$('#menuBtn')?.addEventListener('click',()=>{const n=$('#mobileNav');if(n)n.hidden=!n.hidden});window.addEventListener('hashchange',()=>{const n=$('#mobileNav');if(n)n.hidden=true;route()});window.matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(state.theme==='system')applyTheme()});route();
})();
